### ISSUE TITLE
Error in docs about `Runnable::run` return value

### ISSUE THREAD

**Issue by phil-opp** [smol-rs/async-task#8]
The documentation for `Runnable::run` currently says:

https://github.com/stjepang/async-task/blob/7e1581aae0b94bbe50b65dc615c8d11d7010bbb3/src/runnable.rs#L278-L281

I think one of these `true`s should be a `false`, but I'm not sure which one.

Also, it is not clear how I should deal with the return value (i.e. should I do anything special if it returns true/false?).

**Comment by ghost** [comment]
I have fixed the typo and expanded the comment a bit. Let me know if you feel the latest docs are still not clear enough. Thanks!

**Comment by phil-opp** [comment]
Thanks a lot!
